playerDB = [
    {name: "Cecile",
    powerUpRadius: 1},
    {name: "Regis",
    powerUpRadius: 4},
    {name: "Helen",
    powerUpRadius: 5},
    {name: "Filippo",
    powerUpRadius: 3},
    {name: "Fareaha",
    powerUpRadius: 7},
    {name: "Niccolo",
    powerUpRadius: 4},
    {name: "Amine",
    powerUpRadius: 2},
    {name: "Adele",
    powerUpRadius: 1},
    {name: "Antoine",
    powerUpRadius: 1},
    {name: "Priyanka",
    powerUpRadius: 6},
    {name: "Harnit",
    powerUpRadius: 6},
    {name: "Jean-Nicolas",
    powerUpRadius: 6},
    {name: "Mathis",
    powerUpRadius: 2},
    {name: "Laura",
    powerUpRadius: 1},
    {name: "Chloe",
    powerUpRadius: 1},
    {name: "Mehdi",
    powerUpRadius: 1},
    {name: "Geoffroy",
    powerUpRadius: 8},
    {name: "Heather",
    powerUpRadius: 1},
    {name: "Nicolas",
    powerUpRadius: 3},
    {name: "Abi",
    powerUpRadius: 1},
    {name: "Marie",
    powerUpRadius: 1},
    {name: "Paul",
    powerUpRadius: 2},
    {name: "Nizar",
    powerUpRadius: 4},
];

playerDB = playerDB.slice(0,playerDB.length);
// playerDB = playerDB.slice(0,2);